# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global]
[default.global.parameters]
stack_name = "open-IELTS"

[default.build]
[default.build.parameters]
cached = true
parallel = true

[default.validate]
[default.validate.parameters]
lint = true

[default.deploy]
[default.deploy.parameters]
capabilities = "CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
confirm_changeset = true
resolve_s3 = true
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-33kg1mcprcw6"
s3_prefix = "open-IELTS-syan"
region = "us-east-1"
image_repositories = []
parameter_overrides = "EventBus=\"bus\" FileStoreProject=\"file-store-manager\" Name=\"open-IELTS-syan\" Owner=\"weihengyans@gmail.com\" Project=\"open-IELTS-syan\""
disable_rollback = true
stack_name = "open-IELTS-syan"

[default.package]
[default.package.parameters]
resolve_s3 = true

[default.sync]
[default.sync.parameters]
watch = true

[default.local_start_api]
[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda]
[default.local_start_lambda.parameters]
warm_containers = "EAGER"
