AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  EventBus:
    Type: String
    Default: bus

  FileStoreProject:
    Type: String
    Description: The name of the File Store Project that the event rule resource created by this Template belong to. A Team may own many Projects.
    Default: file-store-manager

  Name:
    Type: String
    Description: >-
      A String that can be used to Identify Resources created by this Template.
      Resources may use this Parameter when creating the Name Tag. The Name Tag
      is commonly used by the AWS Console to provide a friendlier name to
      Resources. This may be used to form part of a Name Tag.
    Default: WeiHengPractice

  Owner:
    Type: String
    Description: >-
      The email address for the Team that owns the Resources created by this
      Template.
    AllowedPattern: ^(.*@gmail\.(io|com|tv),?)+$
    ConstraintDescription: Must be an @mcmaster.ca email address
    Default: weihengyans@gmail.com

  Project:
    Type: String
    Description: >-
      The name of the Project that the Resources created by this Template
      belong to. A Team may own many Projects.
    Default: OpenIELTS

Resources:
  ExternalServicesAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Required actions for clients
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - ssm:GetParameter
              - lambda:InvokeFunction
            Resource:
              - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/*'
              - arn:aws:lambda:*:*:function:*

  
  STSAssumeRole:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Allows STS Assume Role
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Resource:
              - '*'
  
  RegisterInput:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Policies:
          - !GetAtt DynamoDB.Outputs.DatabaseWritePolicyArn
          - !GetAtt DynamoDB.Outputs.DatabaseReadPolicyArn
      CodeUri: open_elt/
      Handler: apigateway_handler.register_input_handler
      Runtime: python3.9
      Architectures:
      - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /client
            Method: post
    
  RetrieveByUserId:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Policies:
          - !GetAtt DynamoDB.Outputs.DatabaseReadPolicyArn
      CodeUri: open_elt/
      Handler: apigateway_handler.retrieve_by_user_id_handler
      Runtime: python3.9
      Architectures:
      - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /user
            Method: get
  
  RetrieveBySessionId:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Policies:
          - !GetAtt DynamoDB.Outputs.DatabaseReadPolicyArn
      CodeUri: open_elt/
      Handler: apigateway_handler.retrieve_by_session_id_handler
      Runtime: python3.9
      Architectures:
      - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /session
            Method: get


  DynamoDB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: dynamodb.yaml
      TimeoutInMinutes: 10
      Parameters:
        Name: !Sub ${Name}
        Owner: !Ref Owner
        Project: !Ref Project

        # !GetAtt DynamoDB.Outputs.TagTableName
        # !GetAtt DynamoDB.Outputs.TagTableARN
        # !GetAtt DynamoDB.Outputs.TagDBTableStreamARN
        # !GetAtt DynamoDB.Outputs.DatabaseReadPolicyArn
        # !GetAtt DynamoDB.Outputs.DatabaseWritePolicyArn

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Join:
        - ''
        - - ApplicationInsights-SAM-
          - Ref: AWS::StackName
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0


  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Fn::Join:
        - ''
        - - ApplicationInsights-SAM-
          - Ref: AWS::StackName
      AutoConfigurationEnabled: 'true'
    DependsOn: ApplicationResourceGroup


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PostApi:
    Description: API Gateway endpoint URL for Prod stage for registering client info input function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/client"
  GetUserIdApi:
    Description: API Gateway endpoint URL for Prod stage for getting client info function based on UserId
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/user"
  GetSessionIdApi:
    Description: API Gateway endpoint URL for Prod stage for getting client info function based on SessionId
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/session"
  RegisterInput:
    Description: Registering client info input Lambda Function ARN
    Value: !GetAtt RegisterInput.Arn
  RetrieveByUserId:
    Description: Getting client info by UserId Lambda Function ARN
    Value: !GetAtt RetrieveByUserId.Arn
  RetrieveBySessionId:
    Description: Getting client info by SessionId Lambda Function ARN
    Value: !GetAtt RetrieveBySessionId.Arn
  RegisterInputIamRole:
    Description: Implicit IAM Role created for RegisterInput function
    Value: !GetAtt RegisterInput.Arn
  RetrieveByUserIdIamRole:
    Description: Implicit IAM Role created for RetrieveByUserId function
    Value: !GetAtt RetrieveByUserId.Arn
  RetrieveBySessionIdIamRole:
    Description: Implicit IAM Role created for RetrieveBySessionId function
    Value: !GetAtt RetrieveBySessionId.Arn
